apiVersion: 1
kind: Pod
metadata:
  name: my-app
  labels:
      app: myapp
      type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
    ports:
      - containerPort: 80
    envFrom:
      secretRef:
        name: app-secret

#kubectl create -f pod-definition.yml
#
#Kind:      Version:
#
#POD        v1
#Service    v1
#Replicaset apps/v1
#Deployment apps/v1
#
#ENV---------------------
#
#envFrom:
#  - secretReF:
#      name: app-config
#
#SINGLE ENV--------------
#
#env:
# - name: DB_Password
#   valueFrom:
#     secretKeyRef:
#       name: app-secret
#       key: DB_Password
#
#Volume------------------
#
#volumes:
#- name: app-secret-volume
#  secret:
#    secretName: app-secret
#
