apiVersion: v1
kind: Service
metadata:
  name: front-app-service
  labels:
    name: front-app-service
    app: demo-app
spec:
  type: NodePort       
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: front-my-app
    app: demo-app
