apiVersion: v1
kind: Pod
metadata:
  name: result-my-app
  labels:
    name: result-my-app
    app: demo-app
spec:
  containers:
    - name: result-my-app
      image: dabizidabi/myapp_result:v1
      ports:
        - containerPort: 80
